spring.application.name=Chinanko
spring.datasource.url=jdbc:postgresql://localhost:5432/chinankodb
spring.datasource.username=postgres
spring.datasource.password=qwe123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Configuración de SpringDoc (Swagger) ---
# Paquetes donde buscar controladores para la documentación
springdoc.packagesToScan=chinanko.chinanko.controller
# Ruta donde se sirve la UI. Acceso: http://localhost:8080/swagger-ui/index.html
springdoc.swagger-ui.path=/swagger-ui.html
# Ruta para los documentos OpenAPI JSON
springdoc.api-docs.path=/v3/api-docs
# Habilita la interfaz de usuario de GraphiQL
spring.graphql.graphiql.enabled=true